### ISSUE TITLE
"Chartes" tab point to wrong file while in "Commanditaires"

### ISSUE THREAD

**Issue by raphaelgodro** [aeglo/website#9]
When we go in the "Commanditaires" tab, the link in the header towards "Chart" is wrong. It points to `http://aeglo.ift.ulaval.ca/files/charte3.0.pdf` and should point towards `http://aeglo.ift.ulaval.ca/files/charte3.1.pdf`

**Comment by Jouramie** [comment]
Done direct en prod!
